parameters:
    car.make: Ford
    car.size: 4
    template.path: /vagrant/studygroup/src/SDPHP/StudyGroup08/Resources/views
    tempalte.cache:
        - cache: /vagrant/studygroup/src/app/cache
services:
    person_driver.class:
        class: \SDPHP\StudyGroup07\Person
        arguments: ["Juan", "driver"]
    car:
        class: \SDPHP\StudyGroup07\Car
        arguments: ["%car.make%", "%car.size%"]
        calls:
            - [addPerson, ["@person_driver.class"] ]
    hello_translation.controller:
        class: \SDPHP\StudyGroup08\Controller\HelloWorldController
        arguments: ["@twig_environment"]

    context:
        class: \Symfony\Component\Routing\RequestContext
    matcher:
        class: \Symfony\Component\Routing\Matcher\UrlMatcher
        arguments: ["%routes%", "@context"]
    resolver:
        class: \SDPHP\SGFramework\Controller\ControllerResolver
        arguments: ["@service_container"]
    listener.router:
        class: \Symfony\Component\HttpKernel\EventListener\RouterListener
        arguments: ["@matcher"]
    subscriber.modify_default:
        class: \SDPHP\StudyGroup08\Event\ModifyDefaultSubscriber
    subscriber.before_after:
        class: \SDPHP\StudyGroup08\Event\BeforeAfterSubscriber
    dispatcher:
        class: \Symfony\Component\EventDispatcher\EventDispatcher
        calls:
             - [addSubscriber, ["@listener.router"]]
             - [addSubscriber, ["@subscriber.before_after"]]
#             - [addSubscriber, ["@subscriber.modify_default"]]
    framework:
        class: \SDPHP\SGFramework\SGFramework
        arguments: ["@dispatcher", "@service_container", "@resolver"]

    # load twig
    twig_loader:
        class: \Twig_Loader_Filesystem
        arguments: ["%template.path%"]

    twig_environment:
        class: \Twig_Environment
        arguments: ["@twig_loader", "%tempalte.cache%"]